### ISSUE TITLE
unable to run examples

### ISSUE THREAD

**Issue by MariusMeiners** [nicolodavis/boardgame.io#321]
I was unable to run the examples as described. 

Steps to reproduce:
pull repo -> npm i -> npm start

os: windows
node: v10.13.0
npm i went through without errors

errorlog: 
```
Error: Cannot find module './tic-tac-toe/game'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Mariu\Documents\programming\boardgame.io\examples\react\server.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at babelWatchLoader (C:\Users\Mariu\Documents\programming\boardgame.io\node_modules\babel-watch\runner.js:50:13)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Mariu\Documents\programming\boardgame.io\node_modules\babel-watch\runner.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at process.on (C:\Users\Mariu\Documents\programming\boardgame.io\node_modules\babel-watch\runner.js:108:21)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by MariusMeiners** [comment]
pulling the repo again solved the issue. Most likely an os problem :)
