### ISSUE TITLE
Firebase error on changing G

### ISSUE THREAD

**Issue by MindsEyeGames** [nicolodavis/boardgame.io#329]
I'm having an issue with using Firebase. The server looks like it starts up fine, and I can see data getting saved on the server, BUT I always see this error message when I make a move:

`(node:22557) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
(node:22557) UnhandledPromiseRejectionWarning: FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined
    at new FirestoreError (/home/cmolini/react/boardgames/test1/node_modules/@firebase/firestore/dist/index.node.cjs.js:348:28)
    at ParseContext.require.ParseContext.createError (/home/cmolini/react/boardgames/test1/node_modules/@firebase/firestore/dist/index.node.cjs.js:18927:16)
    at UserDataConverter.require.UserDataConverter.parseScalarValue (/home/cmolini/react/boardgames/test1/node_modules/@firebase/firestore/dist/index.node.cjs.js:19269:27)
    at UserDataConverter.require.UserDataConverter.parseData (/home/cmolini/react/boardgames/test1/node_modules/@firebase/firestore/dist/index.node.cjs.js:19140:29)
    at /home/cmolini/react/boardgames/test1/node_modules/@firebase/firestore/dist/index.node.cjs.js:19156:41
    at forEach (/home/cmolini/react/boardgames/test1/node_modules/@firebase/firestore/dist/index.node.cjs.js:448:13)
    at UserDataConverter.require.UserDataConverter.parseObject (/home/cmolini/react/boardgames/test1/node_modules/@firebase/firestore/dist/index.node.cjs.js:19155:13)
    at UserDataConverter.require.UserDataConverter.parseData (/home/cmolini/react/boardgames/test1/node_modules/@firebase/firestore/dist/index.node.cjs.js:19114:25)
    at /home/cmolini/react/boardgames/test1/node_modules/@firebase/firestore/dist/index.node.cjs.js:19156:41
    at forEach (/home/cmolini/react/boardgames/test1/node_modules/@firebase/firestore/dist/index.node.cjs.js:448:13)`

The data on the server also does not seem to update correctly after the initial write - for example, every time I move a piece I set a "hasMoved" boolean to true on it, and no pieces depict that change.

This is a sample G state object: [https://pastebin.com/aixZsgfk](https://pastebin.com/aixZsgfk) As you can see, it has no undefined fields (when pieces are taken I just change their "alive" to false) so I don't think I configured it wrong.

Does the Firestore implementation work for anybody else? My game's code is extremely vanilla/close to the examples, so I doubt I'm causing any weird edge cases in G. Am I perhaps configuring the Firebase database incorrectly?

The overall goal I'm trying to do is set up a game server on Google cloud but I'm new to Cloud, Firebase, React, and this framework, so I'm sure something is set wrong somewhere lol

**Comment by p00ya** [comment]
FWIW, I have a working configuration (G is persisted correctly after moves) with boardgame.io@0.31.4 and Cloud Firestore (@firebase/firestore@1.1.2).

Note that undefined values were also popping up in ctx - I fixed one occurrence of this in #381.  You might also want to try again with a recent firebase module (I got a more informative error message which greatly helped in debugging).

**Comment by delucis** [comment]
I think this should be resolved now, but please feel free to re-open if you encounter this again. Firebase Firestore support has been removed from this repository and a replacement implementation is available here instead: https://github.com/delucis/bgio-firebase
