### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#365]
```
(node:21128) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Object.sendAll (/home/dzik/Projects/games/change_management/koa_app/node_modules/boardgame.io/dist/server.js:2524:25)
    at Master.onUpdate (/home/dzik/Projects/games/change_management/koa_app/node_modules/boardgame.io/dist/server.js:2397:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:21128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
Sometime i got this error and to be honest i have no chance to reproduce it, it seems to be completly random and as you can see its reported very poor. What could be reason ? 

When i restar my koa server then everything back to normality i can perform move which previously thrown this error and continue, and then after some time i got this error one more time and so on. Really strange.

**Comment by nicolodavis** [comment]
Haven't seen this error myself, and given that there isn't a sure way to reproduce it, I'll close this for now.  Feel free to re-open if you see this after upgrading to v0.33.
