### ISSUE TITLE
Python bot broken since v0.25.5

### ISSUE THREAD

**Issue by francoijs** [nicolodavis/boardgame.io#379]
I've just realized that the python bot was broken since release 0.25.5 (not broken in 0.25.4).
Here is a trace of the error for reference.
I will have a look and send a PR  ASAP!

```

$ ./tictactoebot.py 
INFO:main:starting bot... (Ctrl-C to stop)
Traceback (most recent call last):
  File "./tictactoebot.py", line 80, in <module>
    main()
  File "./tictactoebot.py", line 63, in main
    client = TicTacToeBot()
  File "./tictactoebot.py", line 37, in __init__
    'player_id': '1'})
  File "/home/francois/workspace/boardgame/boardgame.io/python/examples/tic-tac-toe/boardgameio.py", line 107, in __init__
    socket = io.SocketIO(server, port, wait_for_connection=False)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
StopIteration
```

**Comment by nicolodavis** [comment]
Thanks for looking into this @francoijs!
