### ISSUE TITLE
 Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field ctx._actionPlayersOthers)

### ISSUE THREAD

**Issue by p00ya** [nicolodavis/boardgame.io#381]
# Repro

Versions from yarn.lock:
boardgame.io@0.31.4
@firebase/firestore@1.1.2

I create a server using the 
```
import { Firebase, Server } from 'boardgame.io/server';
const db = new Firebase({ config });
const server = Server({
  db,
  games: [Game],
});
```

The game obj includes TurnOrder.ANY_ONCE:

```
{
  flow: {
    phases: {
      fooPhase: {
        allowedMoves: ['fooMove'],
        movesPerTurn: 1,
        next: 'barPhase',
        turnOrder: TurnOrder.ANY_ONCE,
      },
```

I get the following error:

```
(node:96563) UnhandledPromiseRejectionWarning: Error: Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field ctx._actionPlayersOthers).
    at validateUserInput (foo/node_modules/@google-cloud/firestore/build/src/serializer.js:273:15)
    at Object.validateUserInput (foo/node_modules/@google-cloud/firestore/build/src/serializer.js:268:17)
    at validateDocumentData (foo/node_modules/@google-cloud/firestore/build/src/write-batch.js:622:26)
    at WriteBatch.set (foo/node_modules/@google-cloud/firestore/build/src/write-batch.js:242:9)
    at DocumentReference.set (foo/node_modules/@google-cloud/firestore/build/src/reference.js:337:27)
    at Firebase.set (foo/node_modules/boardgame.io/dist/server.js:2636:17)
    at Master.onSync (foo/node_modules/boardgame.io/dist/server.js:3468:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

# Analysis

The undefined value here is coming from the TurnOrder code:
https://github.com/nicolodavis/boardgame.io/blob/master/src/core/turn-order.js

Note that "others" is not provided as a field to actionPlayers:

```
  ANY_ONCE: {
    first: (G, ctx) => ctx.playOrderPos,
    next: (G, ctx) => ctx.playOrderPos,
    actionPlayers: { all: true, once: true },
    endPhaseOnceDone: true,
  },
```

Then in `setActionPlayers`, this is merged into ctx:

```
  return {
    ...ctx,
    actionPlayers,
    _actionPlayersOnce: arg.once,
    _actionPlayersOthers: arg.others,
  };
```

and then at some point ctx is persisted.   I think the fix is as easy as `actionPlayers: { all: true, once: true, others: false }`.  However, maybe we want something more robust (e.g. filtering out all undefined values in ctx)?

Happy to submit a PR for the "easy" fix if it LGTY.

**Comment by nicolodavis** [comment]
Thanks!  Sure, I'll be happy to look at a PR that adds `others : false`.

Also take a look at https://github.com/nicolodavis/boardgame.io/pull/363.
