### ISSUE TITLE
Moves/events wrapped by plugins sometimes get wrapped twice

### ISSUE THREAD

**Issue by delucis** [nicolodavis/boardgame.io#544]
In putting together #543, I noticed that [`turn.onBegin` called in `StartTurn`](https://github.com/nicolodavis/boardgame.io/blob/b0a5175eb6a7a3656623a6ced640a9c6c3a741ef/src/core/flow.js#L324) seemed to have been wrapped twice by the player plugin’s `fnWrap`.

Here is a demo that logs how a plugin’s `fnWrap` is called:
https://codesandbox.io/s/double-wrapped-plugin-function-kpnbb
Try making a move or ending the turn from the debug UI and see how the calls are nested.

When debugging #543, I also put together a stack trace from the player plugin’s `wrapFn`. Here are the trace results for the two calls triggered by `StartTurn` calling `turn.onBegin`:

<details>
  <summary>Double-wrapped <code>moveFn</code> trace</summary>
  <pre>
    <code>
Trace: fnWrap
  at CustomConsole.trace (internal/console/constructor.js:336:11)
  at trace (/boardgame.io/src/plugins/plugin-player.js:19:15)
  at Object.onBegin (/boardgame.io/src/plugins/main.js:79:10)
  at StartTurn (/boardgame.io/src/core/flow.js:322:5)
  at Process (/boardgame.io/src/core/flow.js:222:15)
  at Object.init (/boardgame.io/src/core/flow.js:845:11)
  at init (/boardgame.io/src/core/initialize.js:64:25)
  at new _ClientImpl (/boardgame.io/src/client/client.js:111:22)
  at Client (/boardgame.io/src/client/client.js:431:10)
  at Object.&lt;anonymous&gt; (/boardgame.io/src/plugins/plugin-player.test.js:116:14)
Trace: fnWrap
  at CustomConsole.trace (internal/console/constructor.js:336:11)
  at trace (/boardgame.io/src/plugins/plugin-player.js:19:15)
  at Proxy.&lt;anonymous&gt; (/boardgame.io/src/plugins/main.js:79:10)
  at Proxy.&lt;anonymous&gt; (/boardgame.io/node_modules/immer/src/immer.js:44:45)
  at Immer.call (/boardgame.io/node_modules/immer/src/immer.js:64:33)
  at produce (/boardgame.io/node_modules/immer/src/immer.js:44:22)
  at /boardgame.io/src/plugins/plugin-player.js:33:17
  at Object.onBegin (/boardgame.io/src/plugins/main.js:79:10)
  at StartTurn (/boardgame.io/src/core/flow.js:322:5)
  at Process (/boardgame.io/src/core/flow.js:222:15)
    </code>
  </pre>
</details>

#### Observations

- The double wrapping seems to impact the turn hooks `onBegin`, `onEnd`, and `onMove`

- So far, I’ve noticed that functions are wrapped as expected (i.e. just once) when:

  - No phases are defined

  - Turn hooks are defined directly _within_ a phase (e.g. `phase: { turn: { onBegin } }`)

**Comment by nicolodavis** [comment]
The problem is that this [code](https://github.com/nicolodavis/boardgame.io/blob/master/src/core/flow.ts#L202) runs in a loop, one for each phase.  However, the turn related hooks might refer to the same global turn hooks if nothing is defined per-phase.  This results in those hooks being double-wrapped.

**Comment by nicolodavis** [comment]
I'm fixing this in the `cleanup` branch that I'm working on.
