### ISSUE TITLE
Unable to run server on localhost ... 

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#710]
This is my simple server : 

```
import { Server } from 'boardgame.io/server';
import { Bridge } from './lib/bridge.js';
import cors from '@koa/cors';

const server = Server({
  games: [Bridge],
});

server.app.use(cors({ origin: '*' }));
server.run(3010);

```
when i try to connect to it it throws : 

```
(node:47605) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ctx' of undefined
    at CreateGameReducer (/Users/grzegorz/play-engine/gameServer/node_modules/boardgame.io/dist/server.js:1477:23)
    at Master.onSync (/Users/grzegorz/play-engine/gameServer/node_modules/boardgame.io/dist/server.js:2388:21)
    at Socket.<anonymous> (/Users/grzegorz/play-engine/gameServer/node_modules/boardgame.io/dist/server.js:2553:28)
    at Socket.emit (events.js:182:13)
    at /Users/grzegorz/play-engine/gameServer/node_modules/socket.io/lib/socket.js:528:12
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

Same client running with multiplayer : Local works as should, what could be the source of problem?

**Comment by pociej** [comment]
My bad, different version of package on client and server
